\chapter*{Remerciements}

\initial{E}n toute transparence, si cette partie trône fièrement dans les premières pages de ce manuscrit, elle est en réalité rédigée bien après le point final du dernier chapitre. En fait, l’ampleur de ma gratitude me semble difficilement exprimable avec des mots. Cependant, je vais essayer – bien que maladroitement - de rendre hommage aux incroyables personnes qui composent mon existence, qui m’ont accepté dans leur espace personnel, qui ont contribué à la qualité de ce travail, mais aussi (et surtout) qui m’ont communiqué l’envie et la joie de faire ce beau métier. 

Il m’a semblé cohérent d’organiser ces remerciements à l’image de cette thèse. Comme ce travail traite de la représentation conceptuelle désignée par un mot, je tenterai d’attribuer aux personnes remerciées un ensemble de mots qui, selon moi, les désignent. 

Mes premiers remerciements et ma profonde gratitude se dirigent vers mes encadrant·e·s, sans qui je ne serais certainement pas en train d’écrire ces quelques lignes, et avec qui j’espère pouvoir continuer à échanger et collaborer encore de nombreuses années. À vous trois, et chacun à votre manière, vous représentez les caractéristiques de la chercheuse que j’aspire à être.

Je remercie chaleureusement ma directrice **Marie Montant**, un modèle d’intelligence, de détermination, d’empathie, et de modestie, que chacun devrait suivre. Marie, merci de m’avoir accordé ta confiance, de m’avoir motivée, canalisée, et guidée tout au long de ce parcours. Ton esprit et ton énergie ont contribué de façon significative à l’évolution de ma pensée, et ainsi à faire de moi la chercheuse que je suis aujourd’hui. Je suis particulièrement reconnaissante de t’avoir eu comme mentor et tellement heureuse de cette belle relation que nous avons développée au-delà du cadre traditionnel. 

Mes pensées se dirigent ensuite naturellement vers mon directeur **Johannes Ziegler**, un chercheur passionné, aux capacités de réflexions surprenantes, et un puits de connaissance hors du commun. Johannes, je te remercie sincèrement pour ta confiance, pour le temps précieux que tu m’as accordé en dépit de tes nombreuses responsabilités et de la charge titanesque de travail que tu abats au quotidien. Le tout sans jamais faiblir, en restant disponible et en faisant tout pour les nombreuses personnes qui t’entourent (on se demande même si tu dors la nuit…). Je m’estime extrêmement chanceuse de t’avoir comme mentor. Merci pour tout ce que tu es et tout ce que tu m’as transmis, parfois même sans t’en rendre compte. 

Enfin, je souhaite adresser de chaleureux remerciements à ma directrice de l’ombre, **Jennifer Coull**, une chercheuse extraordinaire, inspirante, brillante, et modeste, au sourire contagieux et réconfortant. Jenny, je ne te remercierai jamais assez pour tout ce que tu as fait (sans condition ni contrepartie) pour me permettre d’être là où je suis aujourd’hui, mais aussi pour tout ce que tu m’as transmis. Tu es l’une des principales raisons qui font que j’aime ce métier et tu représentes, selon moi, la preuve que l’on peut être à la fois une excellente chercheuse, une femme épanouie, une mère, et une amie. 

Mes remerciements se dirigent à présent vers mon jury de thèse : **Pr. Sylvie Droit-Volet**, **Dr. Ludovic Ferrand**, **Dr. Véronique Boulenger**, et **Dr. Kristof Strijkers**, qui ont accordé un temps précieux pour lire et examiner cette thèse. Je vous remercie également pour votre présence le jour de cette soutenance. Je vous remercie notamment pour ces discussions passionnantes et stimulantes que nous avons eues. À l’avenir, j’espère avoir la chance d’échanger de nouveau avec vous, et, pourquoi pas, collaborer sur des sujets qui nous animent. 

Mes affectueux remerciements à **Christine Assaiante**, qui m’a accueillie, accompagnée, et soutenue tout au long de mon parcours. Christine, je te remercie d’avoir cru en moi et de m’avoir donné la force de continuer dans un moment où je doutais de moi. Je te remercie également pour toutes nos discussions et les précieux apprentissages que tu m’as apportés. 

Je remercie également les deux piliers du Laboratoire de Psychologie Cognitive, **Frédéric Lombardo** et **Colette Pourpe**, pour leur gentillesse, leur travail titanesque, et nos nombreux échanges. 

J’adresse mes remerciements à **Marie-Hélène**, pour sa gentillesse, nos discussions matinales et pour avoir allumé le chauffage d’appoint dans notre bureau tôt le matin avant notre arrivée pour nous éviter de souffrir du froid. 

Mes pensées se dirigent également à mes enseignant·e·s de master au LPNC à Grenoble. Je tiens à remercier tout particulièrement **Christopher Moulin** et **Céline Souchay**, deux chercheur·euses brillant·e·s, les premiers à avoir cru en moi (bien avant moi), qui m’ont transmis leur passion pour la recherche et ont tout fait pour me permettre de suivre cette voie. 

Je souhaite vivement remercier mes amis. Un immense merci à mon très cher et vieil ami, **Thomas Ferrari**, mon Jiminy Cricket à moi, à l’esprit, l’humour (caustique !), la curiosité, et l’humilité incroyables. Peu de mots sont disponibles pour exprimer à quel point je m’estime chanceuse de vivre cette belle (et inconditionnelle) amitié qui fête sa première décennie. Thomas, je te remercie pour m’avoir accompagnée et épaulée toutes ces années. Merci pour ces innombrables et stimulantes discussions de plusieurs heures qui nous paraissent toujours ne durer que quelques minutes. Merci d’être mon ami, simplement, en dépit du temps et de l’espace qui nous séparent. Parce que ta présence dans ma vie, même de loin, participe à faire de moi la personne que je suis et à rendre ma vie si douce. 

Un grand merci à mon cher ami **Jonathan Mirault**, chercheur impliqué et rigoureux, incroyable technicien, et au cœur sur la main. Jon, ma *'dino-patate douce’*, les mots me manquent pour exprimer toute ma reconnaissance, non seulement pour ton amitié mais aussi pour tout ce que tu m’as appris. Sans toi et le temps que tu m’as accordé, je n’en serais pas là aujourd’hui, merci. Merci, pour cette amitié pure et simple qui nous lie, et ces riches moments ensemble, que j’espère encore nombreux. 

Un grand merci à ma très chère amie **Fleur Brun**, jeune fofolle attachante, à l’esprit complexe et farfelu, au cœur tendre, qui a tout de suite pris une place importante dans ma vie. Fleur, *‘Tu fais bien ce que tu veux’*, je suis tellement heureuse de t’avoir dans ma vie, merci pour tous ces moments de bonheur brut, ces bonnes bouff’, ces heures de jeux (quand je gagne), ces fous rires incontrôlables, et d’avoir partagé mon quotidien pendant deux ans. Merci de m’avoir accompagnée, supportée, suivie dans mes folies vertes, culinaires, et musicales. Je suis fière de pouvoir te compter parmi mes amis et espère que cela va durer encore de belles et nombreuses années. 

Je ne saurais comment remercier convenablement mon très cher ami **Jean-Patrice Albrand**, au sourire contagieux, à l’insatiable curiosité, et à la générosité débordante. Jypé, *‘ça va les mollets ?’*, merci pour tous ces instants de bonheur brut, de danses jusqu’au bout de la nuit, de rires, pour les balades nature, les vacances, les bonnes bouff’, ces discussions, ces soirées jeux, et j’en passe. Merci d’avoir toujours été présent, dans les moments de joie mais aussi les moments de doutes, merci de m’avoir accompagnée, écoutée, et reboostée. Mon ami, *mon frérot*, tu participes de façon significative à rendre ma vie intéressante et douce. Et s’il te plaît : ne change jamais !

Merci à **Guillem Bonnafos**, cette machine à la force surhumaine et au mental d’acier, intelligent, drôle, simple, et modeste. Guillem, *‘c’est transcendantal et cosmique, la vérité vraie’*, je te remercie pour ton énergie, de toujours répondre présent, que ce soit pour boire un verre ou pour aider. Aujourd’hui, je suis heureuse de pouvoir te compter parmi mes amis (je l’espère encore très longtemps) et mes humains préférés. **Rebecca Marchetti**, une jeune chercheuse prometteuse, au cœur sur la main et à la force inépuisable. Rebecca, je suis impressionnée et admirative de ton parcours. Merci d’être mon amie et de rendre ma vie si belle. **Manon Rouselle**, ma danseuse déterminée, intelligente, drôle, et douce. Manon, merci pour ton amitié, ta générosité sans limite et ton sourire contagieux. Merci pour ces moments, j’ai hâte de vivre les prochains. Merci à **Julie Lassault**, *‘merci, mais non merci’*, la meuf incroyable (et qui ne s’en rend même pas compte) qui a fait une thèse, retapé une maison, et est devenue mère, le tout en même temps !! Julie, merci de m’avoir remarquée au labo et de m’avoir mise à l’aise. Merci pour ces barres de rire à m’en faire mal au ventre et pour cette amitié qui ne faiblit pas, malgré nos emplois du temps capricieux. Merci à **Simonetta Logreco**, mon rayon de soleil Italien, à la créativité débordante et inarrêtable. Simonetta, *‘Simo’*, quelle rencontre ! Merci de faire partie de ma vie, de m’avoir soutenue, de m’avoir nourrie de tes mets délicieux et de ta culture étonnante. Merci à **Yannick Becker**, artiste et photographe de talent la nuit, génial, généreux et brillant. Yannick, merci pour ton amitié, ton soutien infaillible, pour nos discussions stimulantes et ces cours incroyables que nous avons donnés ensemble. Merci à **Eva Vives**, pour tous ces bons moments passés ensemble, tout particulièrement cette soirée « vin et éthique scientifique » inoubliable. Merci également à **Edouard Alavoine**, cet esprit attachant, drôle et farfelu, pour son amitié et les bons moments passés ensemble, *‘arrrrrrrête’*. Merci à **Ludivine Javouret**, *‘tu vois ce que je veux dire ?’*, pour m’avoir accueillie chez toi, et aidée, à plusieurs reprises, pour les passations dans les écoles. 

Merci à **Maëlle Tixier**, jeune chercheuse dynamique, rigoureuse, et à l’esprit vif. Merci pour cette belle amitié et ton soutien pendant toutes ces années. Nos nombreuses correspondances par mail tout au long de cette thèse ont contribué de façon non négligeable à me donner la force et l’envie de persévérer dans les moments difficiles.

Je remercie vivement mes chers voisin·e·s du 13 qui sont devenus de vrais amis. Par ordre d’arrivée, je remercie d’abord ma chère voisine **Nicole Negrel**, cette femme à l'histoire de vie incroyable qui devrait être publiée, dont la générosité dépasse l’entendement. Nicole, je te remercie pour avoir été une voisine si gentille, et pour tous ces rires que nous avons eus dans le couloir, j’espère que nous en vivrons de nombreux autres.  Merci à **Sixtine**, cette grande et belle femme drôle, déterminée, au cœur sur la main, et aux mille et unes activités (on se demande aussi comment elle trouve le temps de faire tout ça). Sixtine, merci d’avoir toqué à ma porte et d’avoir insisté pour me sortir de ma grotte, merci pour le lombrithé, et merci de rester mon amie en dépit de notre départ. Merci également à **Quentin**, ce génie fou aux deux doctorats (oui, deux !), génial, drôle et généreux, pour nos premiers échanges sur le palier qui stimulent la matière grise, les soirées jeux / bouff’, et pour ce déguisement incroyable. 

Je remercie aussi chaleureusement **Sophie Tinard**, *‘framboise’*, cette femme drôle, généreuse et inspirante qui a été ma première amie sur Mars’. Merci Sophie, pour ta gentillesse et ta simplicité, pour m’avoir accueillie et ‘adoptée’, pour m’avoir laissé entrer dans ton monde, fait découvrir tant de choses et pour tous ces précieux moments ensemble. Merci à **Morgane**, incroyable femme avant d’être une incroyable Maman, la reine du dancefloor. Merci à **Maria**, cette femme géniale, créative et déterminée, pour son amitié et son soutien. J’en profite pour remercier toute l’équipe, affiliée de prés ou de loin à ‘La graine’ : **Mael**, la pile électrique qui a toujours la patate et le sourire, la formidable et sublime **Farah** infatigable et adorable,  **Édouard**, l’ami fidèle et cuisinier hors pair, **Thomas**, discret au cœur tendre, **Clémence**, l’alliance parfaite entre douceur et folie, aux punchlines fatales, **Anthonin** l'aventurier joyeux et attachant, **Max**, au sourire contagieux et aux playlists pointues, *‘il fait lourd non?’*. Je vous suis tellement reconnaissante pour m’avoir accueillie à bras ouverts et pour avoir rendu ma vie Marsienne si belle toutes ces années. Merci pour ces purs moments, que la distance et le temps ne peuvent effacer. 

Je remercie chaleureusement les membres du laboratoire. Merci à **Françoise Vitu-Thibault**, qui a accepté sans hésitation d’apporter son aide et son expertise en Eyetracking. Merci à **Marlène Abadie**, à la fois chercheuse brillante, enseignante dévouée, et une collègue drôle et généreuse. Merci à **F.-Xavier Alario**, ce chercheur rigoureux, à l’esprit vif et aux remarques toujours constructives et intelligentes. Merci à **Pascale Colé**, rigoureuse et passionnée, pour toutes ces discussions stimulantes que nous avons eues.  Merci à **Isabelle Dautriche**, chercheuse passionnée impliquée dans la vie du laboratoire et, pour sa gentillesse et nos échanges toujours riches. Merci à **Jérémy Danna**, chercheur incroyable (e.g., a écrit son HDR à la main), généreux et qui accepte sans hésiter d’aider toute personne qui en aurait besoin (e.g., moi). Enfin, un immense merci à **Jean-Luc Anton**, pour nos échanges toujours stimulants, pour sa gentillesse hors du commun, et pour m’avoir donné confiance en moi à plusieurs reprises (certainement sans le savoir). 

Enfin, j’adresse des remerciements tout particuliers à **Carole Parron**. Si ces remerciements ne pourront malheureusement jamais lui parvenir, je tiens à exprimer ici mes sincères pensées à cette femme extraordinaire. Je la remercie pour avoir été la première chercheuse à m’accueillir au laboratoire avec son large sourire, à avoir été la première à s’être intéressée à moi, la jeune étudiante timide. Aussi, merci Carole pour m’avoir écoutée et motivée à poursuivre, et merci pour nos échanges par mails réconfortants et motivants. 

Un immense merci à l’ensemble de mes collègues doctorant·e·s, post-doctorant·e·s, et chercheur·euses, qui m’ont accompagnée dans cette belle aventure, présentés sans ordre particulier ici : **Karen Davranche, Éric Castet, Ambre Denis-Noël, Leonardo Pinto Arata, Loic Bonnier, Thibault Gajdos, Isabelle Regner, Marjorie Armando, Marco Bressan, Gabriel Weindel, Boris Burle, Maud Rasamimanana, Laure Tosatto, Stéphane Dufau, Agnes Blaye, Christelle Guette, Jean-Baptiste Melmi, Camille Lallement, Jonathan Grainger, Iliana Kotwas, Anaïs Cauna, Felipe Pegado, Aurélie Calabrese, Elisa Gavard, Angélique Roquet, Konstantina Margiotoudi, Yufei Tan, Thomas Chartier, Joël Fagot, Florence Gaunet, Angélique Lamontagne, Adrien Meguerditchian, Arnaud Rey**. 

Enfin, je remercie chaleureusement l’ensemble des participant·e·s de nos études. Je remercie également chaleureusement les enseignant·e·s de l’école La Vernette pour avoir accepté, à deux reprises, de nous accueillir dans leur classe. Je remercie également tous les enfants qui ont participé avec joie et curiosité à ces deux sessions d’expérimentations. Tout ceci n’aurait jamais été possible sans leur participation. 

J’ai également eu la chance incroyable d’enseigner pendant ces années de thèse. Rien n’est plus stimulant et gratifiant que de pouvoir transmettre et échanger sur des sujets passionnants. J’adresse donc mes remerciements chaleureux à l’ensemble des étudiant·e·s à qui j’ai eu l’honneur d’enseigner. Je les remercie pour leur motivation, leurs gentils mots qui m’ont légitimée et donné confiance dans mon enseignement.

Pour terminer (ne dit-on pas *‘le meilleur pour la fin’* ?) il m’importe de remercier ma famille. Tout d’abord, merci à mes parents, dont la générosité, la bienveillance et l’humilité n’ont pas d’égal. Merci non seulement pour votre amour inconditionnel, mais aussi (et surtout) pour m’avoir offert le choix et l’opportunité que vous n’avez jamais eus. Cette thèse n’est rien à côté du travail et des sacrifices que vous avez fournis pour me permettre de faire ce métier. Je suis donc chanceuse, heureuse et fière d’être votre fille.

Merci à **mon père**, une force de la nature inépuisable et hors du commun, dont l’intelligence, la sagesse, la patience et la persévérance m’inspirent et me guident depuis toujours. 
Papa, *‘La cuillère n’existe pas’*. Trouver les mots qui apaisent les maux de son enfant ne doit pas être chose aisée. C’est pourtant avec cette phrase, d’apparence simple, que tu as su me réconforter dans les moments de doute et me donner le courage de persévérer. Sans oublier ton humour, toujours là pour faire rire, en dépit des circonstances. 
Merci à **ma mère**, cette femme qui accomplit des choses extraordinaires sans s’en apercevoir. Sa générosité et son dévouement pour les personnes qui l’entourent n’ont pas de limite. Et, même si elle en doute parfois, ce sont ces traits, couplés à sa curiosité, sa créativité, et sa sensibilité que j’admire et qui me façonnent. Maman, *‘Ma bichette’*. 

Je remercie mes sœurs, **Céline et Mélissa**, de grandes et belles femmes avant d’être de supers mamans, sans qui ma vie aurait été bien vide. Merci pour leur soutien sans faille, leur amour et tous les précieux moments passés ensemble. Je remercie aussi chaleureusement mes deux supers beaux-frères, **Nicolas et Anthony**, qui, chacun à leur façon, m’apportent beaucoup de support et de précieuses leçons de vie. Je suis aussi la fière *‘tatie d’amour’* de trois enfants extraordinaires qui m’offrent de purs instants de bonheur et d’amour. **Capucine**, douce et créative, *‘Papillon’* (ton premier mot). **Pénélope**, drôle et brillante, *‘Je te vois’*. **Tino**, pile sur pattes au cœur sur la main, *‘on va faire un tour de vélo ?’*. 

Mes chaleureuses pensées vont également à **Claire**, **Antoine**, **Ida** et **François**, ma super belle-famille, pour leur gentillesse, leur accueil, et tous les bons moments que nous avons déjà passés ensemble. 

Enfin, mes plus affectueuses pensées et remerciements vont à **Ladislas Nalborczyk**, *'mais nooooon'*, sans aucun doute la personne la plus incroyable qui compose mon existence. Il m’est difficile de ne choisir que quelques mots pour le désigner. Cependant, je dirais : brillant, génial, humble, généreux, empathique. Ladislas, le temps passé avec toi est ce que je possède de plus précieux. Ces moments sont les parfaits cas d’étude de distorsions temporelles, là où le temps objectif mesuré par des outils conventionnels ne correspond en rien au temps subjectif ressenti. Ladislas, mon double, merci … pour tout! Merci pour ces journées et ces nuits entières à ne rien faire d’autre que parler, pour tous ces rires, ces apprentissages qui nous animent tous les deux et tous ces beaux projets. Merci pour ton soutien pendant ces derniers mois de thèse, pour tes mots réconfortants qui m’ont motivée et ont su me donner confiance en moi. Pour finir, merci de me faire vivre cette chose inestimable qu’on appelle l’amour et à laquelle je ne croyais pas avant de te rencontrer.

<!-- \clearemptydoublepage -->
\afterpage{\blankpage}
